name: Build, Push and Deploy Docker Image using GHCR

# This is based on "Publish Docker Container" By GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  DOCKER_COMPOSE_DIR: /opt/jphacks24/oshinoko/
  COMPOSE_FILE: prod-front-docker-compose.yml


jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./TS/oshinoko
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check directory
        run: ls -al

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "prod-front-docker-compose.yml, pyproject.toml"
          target: /opt/jphacks24/oshinoko/
