name: Build, Push and Deploy Docker Image using GHCR

# This is based on "Publish Docker Container" By GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  DOCKER_COMPOSE_DIR: /jphacs24/oshinoko/
  COMPOSE_FILE: prod-front-docker-compose.yml


jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./TS/oshinoko
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Copy prod-front-docker-compose.yml to server
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          scp -o StrictHostKeyChecking=no "$COMPOSE_FILE" "$SSH_USER@$SSH_HOST:$DOCKER_COMPOSE_DIR"
      
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
            cd $DOCKER_COMPOSE_DIR
            docker-compose -f "$COMPOSE_FILE" pull front-oshinoko
            docker-compose -f "$COMPOSE_FILE" up -d --force-recreate front-oshinoko
          EOF
