# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  python-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    

    - name: Install the code linting and formatting tool Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py310
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py310
      continue-on-error: true
    
    - name: Install the type checker mypy
      run: pip install mypy

    - name: Type check with mypy
      run: mypy py --config-file pyproject.toml
